# Generated by Django 3.1.6 on 2021-02-03 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabeceraComandaModel',
            fields=[
                ('cabeceraId', models.AutoField(db_column='cabecera_id', primary_key=True, serialize=False, unique=True)),
                ('cabeceraFecha', models.DateField(db_column='cabecera_fecha', verbose_name='Fecha del Pedido')),
                ('cabeceraTotal', models.DecimalField(db_column='cabecera_total', decimal_places=2, max_digits=5, verbose_name='Total del Pedido')),
                ('cabeceraCliente', models.CharField(db_column='cabecera_cliente', max_length=50, verbose_name='Nombre del Cliente')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'db_table': 't_comanda_cabecera',
            },
        ),
        migrations.CreateModel(
            name='MesaModel',
            fields=[
                ('mesaId', models.AutoField(db_column='mesa_id', primary_key=True, serialize=False)),
                ('mesaNumero', models.CharField(db_column='mesa_numero', max_length=15)),
                ('mesaCapacidad', models.IntegerField(db_column='mesa_capacidad')),
                ('mesaEstado', models.BooleanField(db_column='mesa_estado', default=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'db_table': 't_mesa',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuarioId', models.AutoField(db_column='usu_id', primary_key=True, serialize=False, unique=True)),
                ('usuarioCorreo', models.EmailField(db_column='usu_mail', max_length=50, unique=True, verbose_name='Correo del usuario')),
                ('usuarioNombre', models.CharField(db_column='usu_nombre', max_length=40, verbose_name='Nombre del usuario')),
                ('usuarioApellido', models.CharField(db_column='usu_apellido', help_text='Apellido del usuario', max_length=50, verbose_name='Apellido del usuario')),
                ('usuarioTipo', models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'CAJERO'), (3, 'MOZO')], db_column='usu_tipo', help_text='Tipo del usuario', verbose_name='Tipo del usuario')),
                ('password', models.TextField(db_column='usu_pass', verbose_name='Password del usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 't_usuario',
            },
        ),
        migrations.CreateModel(
            name='DetalleComandaModel',
            fields=[
                ('detalleId', models.AutoField(db_column='detalle_id', primary_key=True, serialize=False)),
                ('detalleCantidad', models.IntegerField(db_column='detalle_cantidad', verbose_name='Cantidad')),
                ('detalleSubtotal', models.DecimalField(db_column='detalle_subtotal', decimal_places=2, max_digits=5, verbose_name='Subtotal inc. IGV')),
                ('cabecera', models.ForeignKey(db_column='cabecera_id', on_delete=django.db.models.deletion.PROTECT, related_name='cabeceraDetalles', to='Facturacion.cabeceracomandamodel', verbose_name='Cabecera')),
                ('inventario', models.ForeignKey(db_column='inventario_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventarioDetalles', to='Almacen.inventariomodel', verbose_name='Inevntario')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'db_table': 't_comanda_detalle',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteModel',
            fields=[
                ('comprobanteId', models.AutoField(db_column='comprobante_id', primary_key=True, serialize=False, unique=True)),
                ('comprobanteSerie', models.CharField(db_column='comprobante_serie', max_length=4, verbose_name='Serie del Comprobante')),
                ('comprobanteNumero', models.IntegerField(db_column='comprobante_numero', verbose_name='Numero del Comprobante')),
                ('comprobanteCliIdentificacion', models.CharField(db_column='comprobante_identificacion', max_length=11, verbose_name='Identificacion del Cliente')),
                ('comprobantePdf', models.TextField(db_column='comprobante_pdf', verbose_name='PDF del Comprobante')),
                ('comprobanteCdr', models.TextField(db_column='comprobante_cdr', verbose_name='Codigo de Respuesta del Comprobante')),
                ('comprobanteXML', models.TextField(db_column='comprobante_xml', verbose_name='XML del Comprobante')),
                ('cabecera', models.OneToOneField(db_column='cabecera_id', on_delete=django.db.models.deletion.CASCADE, to='Facturacion.cabeceracomandamodel', verbose_name='Comanda')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'db_table': 't_comprobante',
            },
        ),
        migrations.AddField(
            model_name='cabeceracomandamodel',
            name='mesa',
            field=models.ForeignKey(db_column='mesa_id', on_delete=django.db.models.deletion.PROTECT, related_name='mesaComandas', to='Facturacion.mesamodel', verbose_name='Mesa'),
        ),
        migrations.AddField(
            model_name='cabeceracomandamodel',
            name='usuario',
            field=models.ForeignKey(db_column='mesero_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarioComandas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
