# Generated by Django 3.1.6 on 2021-02-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0004_auto_20210210_2011'),
        ('Facturacion', '0002_cabeceracomandamodel_cabeceraestado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariomodel',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AddField(
            model_name='comprobantemodel',
            name='comprobanteTipo',
            field=models.IntegerField(db_column='comprobante_tipo', default=0, verbose_name='Tipo de Comprobante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cabeceracomandamodel',
            name='cabeceraCliente',
            field=models.CharField(db_column='cabecera_cliente', max_length=50, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='cabeceracomandamodel',
            name='cabeceraEstado',
            field=models.CharField(db_column='cabecera_estado', default='ABIERTO', max_length=50, verbose_name='Estado del pedido'),
        ),
        migrations.AlterField(
            model_name='cabeceracomandamodel',
            name='cabeceraFecha',
            field=models.DateField(db_column='cabecera_fecha', verbose_name='Fecha del pedido'),
        ),
        migrations.AlterField(
            model_name='cabeceracomandamodel',
            name='cabeceraTotal',
            field=models.DecimalField(db_column='cabecera_total', decimal_places=2, max_digits=5, verbose_name='Total del pedido'),
        ),
        migrations.AlterField(
            model_name='comprobantemodel',
            name='cabecera',
            field=models.OneToOneField(db_column='cabecera_id', on_delete=django.db.models.deletion.CASCADE, related_name='comanda_cabecera', to='Facturacion.cabeceracomandamodel', verbose_name='Comanda'),
        ),
        migrations.AlterField(
            model_name='comprobantemodel',
            name='comprobanteCdr',
            field=models.TextField(db_column='comprobante_cdr', verbose_name='Codigo de Respuesta del comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobantemodel',
            name='comprobanteCliIdentificacion',
            field=models.CharField(db_column='comprobante_identificacion', max_length=11, verbose_name='Identificacion del cliente'),
        ),
        migrations.AlterField(
            model_name='comprobantemodel',
            name='comprobanteNumero',
            field=models.IntegerField(db_column='comprobante_numero', verbose_name='Numero del comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobantemodel',
            name='comprobantePdf',
            field=models.TextField(db_column='comprobante_pdf', verbose_name='Pdf del comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobantemodel',
            name='comprobanteSerie',
            field=models.CharField(db_column='comprobante_serie', max_length=4, verbose_name='Serie del comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobantemodel',
            name='comprobanteXML',
            field=models.TextField(db_column='comprobante_xml', verbose_name='XML del comprobante'),
        ),
        migrations.AlterField(
            model_name='detallecomandamodel',
            name='detalleSubtotal',
            field=models.DecimalField(db_column='detalle_subtotal', decimal_places=2, max_digits=5, verbose_name='SubTotal inc IGV'),
        ),
        migrations.AlterField(
            model_name='detallecomandamodel',
            name='inventario',
            field=models.ForeignKey(db_column='inventario_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventarioDetalles', to='Almacen.inventariomodel', verbose_name='Inventario'),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='password',
            field=models.TextField(db_column='usu_pass', verbose_name='Contraseña del usuario'),
        ),
    ]
