# Generated by Django 3.1.6 on 2021-02-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0003_inventariomodel_inventarioprecio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariomodel',
            name='inventarioCantidad',
            field=models.IntegerField(db_column='inventario_cantidad', verbose_name='Cantidad del plato'),
        ),
        migrations.AlterField(
            model_name='inventariomodel',
            name='inventarioPrecio',
            field=models.DecimalField(db_column='inventario_precio', decimal_places=2, max_digits=5, verbose_name='Precio del plato'),
        ),
    ]
